### ISSUE TITLE
Edge case, Slow solve ROS environment

### ISSUE THREAD

**Issue by ruben-arts** [mamba-org/rattler#278]
I found a set of dependencies that makes the solve particularly slow. 

```toml
[project]
name = "test"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ruben Arts <ruben.arts@hotmail.com>"]
channels = ["conda-forge", "robostack-staging"]
platforms = ["linux-64"]

[tasks]

[dependencies]
yourdfpy = "0.0.53.*"
numpy = "1.25.2.*"
ros-humble-desktop = "0.10.0.*"
ros-humble-navigation2 = "1.1.5.*"
opencv = "4.6.0.*"
rerun-sdk = "0.8.0.*"
ros-humble-turtlebot3-gazebo = "2.2.5.*"
ros-humble-turtlebot3 = "2.1.5.*"
gazebo = "11.12.0.*"
```
Solve took 4 minutes.

where `micromamba create` takes only 11 sec on this:
```yaml
name: rerun
channels:
  - conda-forge
  - robostack-staging
dependencies:
  - ros-humble-desktop
  - gazebo
  - ros-humble-navigation2 
  - ros-humble-turtlebot3 
  - ros-humble-turtlebot3-gazebo
  - numpy
  - opencv
  - yourdfpy
  - rerun-sdk
 ```
 Takes 11 seconds

**Comment by baszalmstra** [comment]
Did you also try adding the versions to the environment?

**Comment by ruben-arts** [comment]
I'm not getting what version you mean?

**Comment by wolfv** [comment]
Also the order of packages is (unfortunately) relevant

**Comment by baszalmstra** [comment]
> I'm not getting what version you mean?

Well the `pixi.toml` file includes version constraints, the `environment.yml` does not. The equivalent `environment.yml` would be:

```yaml
name: rerun
channels:
  - conda-forge
  - robostack-staging
dependencies:
  - yourdfpy 0.0.53.*
  - numpy 1.25.2.*
  - ros-humble-desktop 0.10.0.*
  - ros-humble-navigation2 1.1.5.*
  - opencv 4.6.0.*
  - rerun-sdk 0.8.0.*
  - ros-humble-turtlebot3-gazebo 2.2.5.*
  - ros-humble-turtlebot3 2.1.5.*
  - gazebo 11.12.0.*
```
