### ISSUE TITLE
UrlOrPath - store absolute Windows URLs with `file:///`?

### ISSUE THREAD

**Issue by wolfv** [mamba-org/rattler#615]
I am looking at some issues we encountered with absolute paths on Windows. 

If I use the following in a pixi.toml file:

```toml
[pypi-dependencies]
minimal-project = { path = "C:/Users/wolfv/Programs/pixi/examples/pypi-source-deps/minimal-project" }
```

Then it works once, but upon rechecking fails because it can't find the corresponding package. In the lockfile we find:

```
      - pypi: C:/Users/wolfv/Programs/pixi/examples/pypi-source-deps/minimal-project
```

This can be deserialized as a URL, so that's where the failure comes from. We make the distinction for relative paths (because they cannot be stored as `file:///` URL. I am wondering if we should deserialize a `file:///C:/...` URL to Path and fix the problem that way.

Or we don't allow absolute paths.
